#You are given two strings s and t.
#String t is generated by random shuffling string s and then add one more letter at a random position.
#Return the letter that was added to t.
def findTheDifference(s, t):
    char_count = {}
    
    for char in s:
        char_count[char] = char_count.get(char, 0) + 1
    
    for char in t:
        if char_count.get(char, 0) == 0:
            return char
        char_count[char] -= 1
    
    return ''  # This line should never be reached if input is valid